"""empty message

Revision ID: 80937f5d195f
Revises: 9999422a985d
Create Date: 2023-04-11 21:22:57.707796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80937f5d195f'
down_revision = '9999422a985d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
